# Site settings
title: Kuthwala
header-img: "img/screenshot.jpg"
email: toolboxgames@gmail.com
copyright_name: Toolbox Studios
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://github.com/ToolboxStudio/toolboxstudio.github.io"



# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
