# Site settings
title: Kuthwala
header-img: "img/screenshot.jpg"
email: toolboxgames@gmail.com
copyright_name: Toolbox Studios
baseurl: ""



# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
